introduced POM and Page Factory
PramodKumarYadav/drona pull request #32
Opened 2021-06-05 11:04 UTC by Bookanakere

I added page object model and ran test using page factory. I took sometime to get this right, but it was a very interesting assignment :-)

2021-06-07 06:58 UTC, PramodKumarYadav requested changes

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +
- [x] extra space

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +public class SauceDemoLogin {
- [x] Class name becomes only Login.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +    WebElement Username;
- [x] Add an extra spacing after each field element.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +    WebElement Password;
- [x] Make all fields private.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +    WebElement Username;
- [x] In java Class names are PascalCase and field names and method names are camelCase. So to rename all fields to camelcase.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +    public void enterUsername(String UserValue) {
- [x] In java we normally use setField and getField. So we rename our methods to setUsername and setPassword.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +    public void enterPassword(String PasswordValue) {
- [x] rename all parameter names without postText Value.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +
We have an extra field here.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +    public void loginToSauceDemo(String UserValue, String PasswordValue) {
- [x] rename method to login.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +        this.enterUsername(UserValue);
- [x] setUsername is enough (we dont have to give this.methodname)

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +    public void loginToSauceDemo(String UserValue, String PasswordValue) {
- [ ] Except this method that we want to use in our tests, make all other methods private (so that they dont show up in intellij intellsense popup)

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +
remove the extra space - ideally should be taken care by editorconfig.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/tests/LoginTest.java
> +package com.saucedemo.tests;
Steps to follow. 
- First delete this class.
- stage and commit this. 
- now you can rename your logintestsaucelab to LoginTest.
- - stage and commit. and everything should be fine.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +package com.saucedemo.pages;
- [x] move the package to src. In tests we only keep tests.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +package com.saucedemo.tests;
Lets rename our class as UglyLoginTest and we will rename it later when we have removed all ugliness out of it.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +
- [x] remove the extra space.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +public class LoginTestWithPageFactory {
rename method to OurUglyLoginTest

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +    WebDriver driver;
driver also private

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +    WebDriver driver;
- [x] driver to be private.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +    SauceDemoLogin Login;
- [x] Login should be login.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +        Login = new SauceDemoLogin(driver);
- [x] Move login initialization to beforeEach method (in future we will do it at field level but for now, this is good enough).

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +        String AppURL = "https://www.saucedemo.com/";
- [x] These two lines belong to Login class. So can be moved there.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +    @AfterEach
- [x] This actually address one of our issues that failing tests did not close the browser.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +    public void assertThatAValidUserCanLogin(String Username, String Password) {
- [x] parameters are to be camelCase.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +        assertEquals(loginError, "Epic sadface: Sorry, this user has been locked out.");
- [x] In junit 5, it is expected first, actual later. So hardcoded values come first and then application values.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +        String loginError = Login.getLoginLockOutError();
- [x] give spacing between tests to make them more readable.

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +    public String getLoginTitle() {
- [x] This becomes just getTitle (since we are already on Login page)

2021-06-07 06:58 UTC, PramodKumarYadav commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +        String pageTitle = Login.getLoginTitle();
- [x] Since page Title is really only used once, we can move the method to assert statement.

2021-06-07 11:46 UTC, Bookanakere commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +    WebDriver driver;
done

2021-06-07 12:03 UTC, Bookanakere commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +    public void loginToSauceDemo(String UserValue, String PasswordValue) {
we use a few methods for assertion. except those, I have made all other fields, variables and methods private

2021-06-07 12:08 UTC, Bookanakere commented on src/test/java/com/saucedemo/tests/LoginTest.java
> +package com.saucedemo.tests;
done.

2021-06-07 12:08 UTC, Bookanakere commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +package com.saucedemo.tests;
done :)

2021-06-07 12:10 UTC, Bookanakere commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +public class LoginTestWithPageFactory {
which method? I already named the class as UglyLoginTest.Not sure, which method you are referring to, here

2021-06-07 12:16 UTC, Bookanakere commented on src/test/java/com/saucedemo/tests/LoginTestWithPageFactory.java
> +    @AfterEach
no action

2021-06-08 16:21 UTC, Bookanakere commented on src/test/java/com/saucedemo/pages/SauceDemoLogin.java
> +package com.saucedemo.pages;
moved

2021-06-08 16:46 UTC, PramodKumarYadav approved these changes

2021-06-08 16:46 UTC, merged