Added framework requirements and test objectives
PramodKumarYadav/drona pull request #8
Opened 2021-05-29 06:44 UTC by Bookanakere

Hi Pramod, 

Instead of updating the existing readme file, I created two new files one for requirements and the other one for test objectives. Could you please take a look?

Regards,
Rashmi

2021-05-29 10:47 UTC, PramodKumarYadav commented
> Hi Pramod,
> 
> Instead of updating the existing readme file, I created two new files one for requirements and the other one for test objectives. Could you please take a look?
> 
> Regards,
> Rashmi

So in general, you only have one readme.md file Rashmi. Idea is any new team member can get everything they need from one readme.md file. You can give a link of one file to another but generically its one readme.md file per project. So maybe you can merge changes and put them into one file.

2021-05-29 15:16 UTC, PramodKumarYadav commented
updating readme file in this PR.

2021-05-29 15:45 UTC, Bookanakere commented
Hi Pramod, I have resolved the conflicts and pushed the updated branch to remote. Please take a look and approve the PR.

PS: Turns out, I had to stage the file again before committing. Thats why I was facing the issue with commit.

2021-05-29 20:56 UTC, PramodKumarYadav commented
> Hi Pramod, I have resolved the conflicts and pushed the updated branch to remote. Please take a look and approve the PR.
> 
> PS: Turns out, I had to stage the file again before committing. Thats why I was facing the issue with commit.

Nice. If I would have seen two files (one in staging and one with changes, it was easy to track but lack of visibility made it difficult to see what was going on). Maybe lets do zoom from tomorrow if it works better?

2021-05-29 20:59 UTC, PramodKumarYadav requested changes

2021-05-29 20:59 UTC, PramodKumarYadav commented on README.md
>  # Files that matters:
- [ ] this part of line is duplicate from above (and maybe also next 2/3 lines). This should also let you get some more practise on what needs to be done in this case. We can discuss more tomorrow.

2021-05-30 12:07 UTC, PramodKumarYadav approved these changes

2021-05-30 12:07 UTC, merged